services:
  app-dev:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: partsfrio-dev
    volumes:
      - .:/var/www/html
      - storage_dev:/var/www/html/storage
      - env_dev:/var/www/html/.env
    depends_on:
      - postgres
      - svfe-api-firmador

  app-prod:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: partsfrio-prod
    volumes:
      - .:/var/www/html
      - storage_prod:/var/www/html/storage
      - env_prod:/var/www/html/.env
    depends_on:
      - postgres
      - svfe-api-firmador

  svfe-api-firmador:
    image: svfe/svfe-api-firmador:v20230109
    container_name: svfe-api-firmador
    ports:
      - '8113:8113'
    volumes:
      - firmador_temp:/uploads

  postgres:
    image: postgres:15
    container_name: nexus-postgres
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"

  nginx:
    image: nginx:stable
    container_name: partsfrio-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_certs:/etc/nginx/certs
    depends_on:
      - app-prod
      - app-dev

volumes:
  pgdata:
  firmador_temp:
  storage_dev:
  storage_prod:
  env_dev:
  env_prod:
  nginx_certs: