services:

  postgres:
    image: postgres:15
    container_name: nexus-postgres
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-dev08_db} -d postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - partsfrio-net

  svfe-api-firmador:
    image: svfe/svfe-api-firmador:v20230109
    container_name: svfe-api-firmador
    ports:
      - '8113:8113'
    volumes:
      - firmador_temp:/uploads
    networks:
      - partsfrio-net

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: nexus-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - storage_prod:/var/www/html/storage
    depends_on:
      postgres:
        condition: service_healthy
      svfe-api-firmador:
        condition: service_started
    networks:
      - partsfrio-net

  nginx:
    image: nginx:alpine
    container_name: partsfrio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/dev.conf:ro
      - ./docker/nginx/certbot.conf:/etc/nginx/conf.d/certbot.conf:ro
      - certbot-etc:/etc/letsencrypt
      - public-data:/var/www/html/public
    depends_on:
      - app
    networks:
      - partsfrio-net
    read_only: true

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - public-data:/var/www/html/public
    command: certonly --webroot --webroot-path=/var/www/html/public \
      --email bitgensv@gmail.com --agree-tos --no-eff-email \
      -d nexus.isolu.tech -d www.nexus.isolu.tech
    depends_on:
      - nginx
    networks:
      - partsfrio-net
    restart: on-failure

volumes:
  pgdata:
  firmador_temp:
  storage_prod:
  certbot-etc:
  certbot-var:
  public-data:

networks:
  partsfrio-net:
    external: true
