version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: partsfrio-dev
    ports:
      - '9001:9000' # expuesto para Nginx host
    volumes:
      - .:/var/www/html
      - storage_dev:/var/www/html/storage
      - ./env_dev:/var/www/html/.env
    depends_on:
      - postgres
      - svfe-api-firmador
    networks:
      - partsfrio-net

  app-prod:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: partsfrio-prod
    ports:
      - '9000:9000' # expuesto para Nginx host
    volumes:
      - .:/var/www/html
      - storage_prod:/var/www/html/storage
      - ./env_prod:/var/www/html/.env
    depends_on:
      - postgres
      - svfe-api-firmador
    networks:
      - partsfrio-net

  svfe-api-firmador:
    image: svfe/svfe-api-firmador:v20230109
    container_name: svfe-api-firmador
    ports:
      - '8113:8113'
    volumes:
      - firmador_temp:/uploads
    networks:
      - partsfrio-net

  postgres:
    image: postgres:15
    container_name: nexus-postgres
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - '5432:5432'
    networks:
      - partsfrio-net

volumes:
  pgdata:
  firmador_temp:
  storage_dev:
  storage_prod:
  env_dev:
  env_prod:

networks:
  partsfrio-net:
    external: true
